implement /product-properties endpoint
NASA-PDS/registry-api pull request #322
Opened 2023-04-21 00:20 UTC by alexdunnjpl

## 🗒️ Summary
Implements a new endpoint, /product-properties, which returns metadata about the searchable fields which users may use in their raw queries (`q=`)

This is pulled directly from the `registry` OpenSearch index and is thus fast and reliable.

## ⚙️ Test Data and/or Report
Need to add a Postman test for this, but that can wait until Monday

## ♻️ Related Issues
Fixes #277

2023-04-21 00:32 UTC, alexdunnjpl commented
@tloubrieu-jpl is the postman collection in service/src/test/resources actually supposed to contain any tests, or just a sample set of requests?  Can't tell if it's the latter or if I'm just missing something silly.

2023-04-21 14:34 UTC, nutjob4life approved these changes

2023-04-25 19:01 UTC, tloubrieu-jpl requested changes
I am not approving it yet because some point requires discussion.

2023-04-25 19:01 UTC, tloubrieu-jpl commented on model/swagger.yml
> +  /product-properties:
I was thinking of `/properties` as end-points. /products-properties sounds redundant to me. However `/products/properties` would make sense but there might be difficulties for the implemention, since 'properties' would be considered as a lid or lidvid....

2023-04-25 19:01 UTC, tloubrieu-jpl commented on model/swagger.yml
> +          $ref: "#/components/responses/Plural"
I think we should have a specific response format for the properties, Plural is for responses returning a list of products.

2023-04-25 19:01 UTC, tloubrieu-jpl commented on service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaProductsTransmuter.java
> +    String registryIndexName = this.getConnection().getRegistryIndex();
I don't know if that is here, but I was expecting the response to be a bit less OpenSearch/ElasticSearch specific, especially the types, keyword is not meaningful here. We need to find something more explicit outside the context of OpenSearch.

2023-04-25 20:04 UTC, alexdunnjpl commented on model/swagger.yml
> +  /product-properties:
Yeah, the overload with `/products/{identifier}` was the motivation for the (admittedly awkward) naming.  I think the only acceptable approach is to find the most semantically-clear root path name we can.

2023-04-25 20:05 UTC, alexdunnjpl commented on model/swagger.yml
> +          $ref: "#/components/responses/Plural"
This was an oversight on my part, good catch.  Will fix.

2023-04-25 20:08 UTC, alexdunnjpl commented on service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaProductsTransmuter.java
> +    String registryIndexName = this.getConnection().getRegistryIndex();
What you're seeing is the result of me just dumping the document without further manipulation (because the fine details of what you/Jordan want from this endpoint are pending discussion).

We can map these however you like (for example, mapping instances of `keyword` to `string` since that's what a `keyword` is in a user search context).

2023-04-25 21:28 UTC, alexdunnjpl commented on model/swagger.yml
> +  /product-properties:
meeting decision: `/properties` (unless working group suggests otherwise)

2023-04-25 21:29 UTC, alexdunnjpl commented on service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaProductsTransmuter.java
> +    String registryIndexName = this.getConnection().getRegistryIndex();
meeting decision (tentative): map OS types to `["string", "float", "integer", "boolean"]`

2023-04-25 23:49 UTC, tloubrieu-jpl commented
@alexdunnjpl regarding your question on test in postman, we are having a few. They can be found in the `Test` tab of each request. See screenshot:
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/60993872/234431802-508666ce-4ee3-4a18-b126-03caac6c3880.png">

2023-04-26 00:20 UTC, alexdunnjpl commented on model/swagger.yml
> +  /product-properties:
addressed in 5120fad8

2023-04-26 00:20 UTC, alexdunnjpl commented on service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaProductsTransmuter.java
> +    String registryIndexName = this.getConnection().getRegistryIndex();
addressed in 5120fad8

2023-04-26 00:20 UTC, alexdunnjpl commented on model/swagger.yml
> +          $ref: "#/components/responses/Plural"
addressed in 5120fad8

2023-04-26 00:22 UTC, alexdunnjpl commented
> @alexdunnjpl regarding your question on test in postman, we are having a few. They can be found in the `Test` tab of each request. See screenshot: <img alt="image" width="1275" src="https://user-images.githubusercontent.com/60993872/234431802-508666ce-4ee3-4a18-b126-03caac6c3880.png">

@tloubrieu-jpl where are you pulling that from?  Loading [the service tests file from this repository](./service/src/test/resources/postman_collection.json) doesn't populate the tests tab with anything.

2023-04-26 04:14 UTC, tloubrieu-jpl commented
Hi @alexdunnjpl , you are right the file you are using is obsolete and should be removed. The one to use is in the registry repository https://github.com/NASA-PDS/registry/blob/main/docker/postman/postman_collection.json
Sorry about that.

2023-04-28 20:02 UTC, alexdunnjpl commented
@tloubrieu-jpl please review at your leisure (I think we ironed out the outstanding questions?)

Type stuff is at the following locations:
https://github.com/NASA-PDS/registry-api/pull/322/files#diff-efe8b5acb4310cc66513c73b36c8564a1aac7efcfd581be3c8bf0c1411f190a1R1307
https://github.com/NASA-PDS/registry-api/pull/322/files#diff-7bb6eb16a239a0e1d6422eaf4cece3577003084597f76d4ec0c2b8bdc7e0a673R148

2023-04-28 20:23 UTC, al-niessner approved these changes

2023-05-01 16:44 UTC, alexdunnjpl commented
Bypassing requested-changes block due to more-recent approval by other code owner

2023-05-01 16:44 UTC, merged